<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>net.ptidej</groupId>
	<artifactId>all-ptidej</artifactId>
	<version>1.0.0</version>
	<name>Ptidej Tool Suite</name>
	<packaging>pom</packaging>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.release>25</maven.compiler.release>
		<maven.test.redirectTestOutputToFile>true</maven.test.redirectTestOutputToFile>
	</properties>

	<build>    
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-install-plugin</artifactId>
					<version>3.1.1</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.15.0</version>
					<configuration>
						<release>${maven.compiler.release}</release>
						<compilerArgs>
							<arg>-Xlint:deprecation</arg>
							<arg>-Xlint:unchecked</arg>
						</compilerArgs>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>3.5.6</version>
					<configuration>
						<excludes>
							<!-- Excluded on purpose -->
							<exclude>**/*Test.java</exclude>
						</excludes>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>3.5.0</version>
					<executions>
						<execution>
							<goals>
								<goal>test-jar</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>build-helper-maven-plugin</artifactId>
					<version>3.0.0</version>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.jdom</groupId>
				<artifactId>jdom2</artifactId>
				<version>2.0.6.1</version>
			</dependency>
			<dependency>
				<groupId>org.apache.lucene</groupId>
				<artifactId>lucene-core</artifactId>
				<version>2.3.2</version>
			</dependency>
			<dependency>
				<groupId>org.apache.ant</groupId>
				<artifactId>ant</artifactId>
				<version>1.7.1</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.eclipse.jdt</groupId>
				<artifactId>org.eclipse.jdt.core</artifactId>
				<version>3.34.0</version>
			</dependency>
			<dependency>
				<groupId>org.eclipse.platform</groupId>
				<artifactId>org.eclipse.core.runtime</artifactId>
				<version>3.27.0</version>
			</dependency>
			<dependency>
				<groupId>org.eclipse.platform</groupId>
				<artifactId>org.eclipse.core.resources</artifactId>
				<version>3.15.0</version>
			</dependency>
			<dependency>
				<groupId>com.thoughtworks.xstream</groupId>
				<artifactId>xstream</artifactId>
				<version>1.4.20</version>
			</dependency>
			<dependency>
				<groupId>org.antlr</groupId>
				<artifactId>antlr-runtime</artifactId>
				<version>3.5.3</version>
			</dependency>
			<dependency>
				<groupId>org.aspectj</groupId>
				<artifactId>aspectjtools</artifactId>
				<version>1.6.2</version>
			</dependency>
			<dependency>
				<groupId>net.java.dev.javacc</groupId>
				<artifactId>javacc</artifactId>
				<version>7.0.12</version>
			</dependency>
			<dependency>
				<groupId>com.github.stephenc.jcip</groupId>
				<artifactId>jcip-annotations</artifactId>
				<version>1.0-1</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.xmlgraphics</groupId>
				<artifactId>batik-anim</artifactId>
				<version>1.16</version>
				<exclusions>
					<exclusion>
						<groupId>xml-apis</groupId>
						<artifactId>xml-apis</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.apache.xmlgraphics</groupId>
				<artifactId>batik-svggen</artifactId>
				<version>1.16</version>
			</dependency>
			<dependency>
				<groupId>org.apache.xmlgraphics</groupId>
				<artifactId>batik-transcoder</artifactId>
				<version>1.16</version>
			</dependency>
			<dependency>
				<groupId>org.apache.xmlgraphics</groupId>
				<artifactId>batik-codec</artifactId>
				<version>1.16</version>
			</dependency>
			<dependency>
				<groupId>net.sf.trove4j</groupId>
				<artifactId>trove4j</artifactId>
				<version>3.0.3</version>
			</dependency>
			<dependency>
				<groupId>au.com.bytecode</groupId>
				<artifactId>opencsv</artifactId>
				<version>2.4</version>
			</dependency>
			<dependency>
				<groupId>com.ibm.toad</groupId>
				<artifactId>cfparse</artifactId>
				<version>1.0</version>
			</dependency>
			<dependency>
				<groupId>javassist</groupId>
				<artifactId>javassist</artifactId>
				<version>1.0</version>
			</dependency>
			<dependency>
				<groupId>JIProlog</groupId>
				<artifactId>JIProlog</artifactId>
				<version>1.0</version>
			</dependency>
			<dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-core</artifactId>
				<version>2.19.0</version>
			</dependency>
			<dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-api</artifactId>
				<version>2.19.0</version>
			</dependency>
			<dependency>
				<groupId>commons-io</groupId>
				<artifactId>commons-io</artifactId>
				<version>2.21.0</version>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-lang3</artifactId>
				<version>3.20.0</version>
			</dependency>
			<dependency>
				<groupId>org.apache.bcel</groupId>
				<artifactId>bcel</artifactId>
				<version>6.11.0</version>
			</dependency>
			<dependency>
				<groupId>junit</groupId>
				<artifactId>junit</artifactId>
				<version>4.13.2</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<modules>
		<module>Caffeine</module>
		<module>Caffeine Analyses</module>
		<module>Caffeine Examples</module>
		<module>Caffeine Tests</module>
		<module>CPL</module>
		<module>DeMIMA</module>
		<module>DeMIMA Solver 3</module>
		<module>DeMIMA Solver 4</module>
		<module>DeMIMA Solver Fingerprints</module>
		<module>DeMIMA Solver Occurrence Generator</module>
		<module>DeMIMA UI</module>
		<module>DeMIMA UI Analyses</module>
		<module>DeMIMA UI AspectJ</module>
		<module>DeMIMA UI C++</module>
		<module>DeMIMA UI Layouts</module>
		<module>DeMIMA UI Primitives AWT</module>
		<!-- TODO Add this module                      -->
		<!-- <module>DeMIMA UI Primitives SWT</module> -->
		<module>DeMIMA UI Viewer</module>
		<module>DeMIMA UI Viewer AWT</module>
		<module>DeMIMA UI Viewer Extensions</module>
		<module>DeMIMA UI Viewer Standalone Swing</module>
		<module>EPI</module>
		<module>JChoco</module>
		<module>MoDeC Metamodel</module>
		<module>MoDeC Solver</module>
		<module>PADL</module>
		<module>PADL Analyses</module>
		<module>PADL Code-Diagram Comparison</module>
		<module>PADL Creator AOL</module>
		<module>PADL Creator AspectJ</module>
		<module>PADL Creator C# v1</module>
		<module>PADL Creator C# v2</module>
		<module>PADL Creator C++ (Eclipse)</module>
		<module>PADL Creator C++ (JavaCC)</module>
		<module>PADL JNI</module>
		<module>PADL Creator ClassFile</module>
		<module>PADL Creator JavaFile (Eclipse)</module>
		<module>PADL Creator JavaFile (Eclipse) Parser</module>
		<module>PADL Creator JavaFile (JavaC)</module>
		<module>PADL Creator JavaFile (JavaC) Parser</module>
		<module>PADL Creator JavaFile-ClassFile Tests</module>
		<module>PADL Creator MSE</module>
		<module>PADL Creator XMI</module>
		<module>PADL Design Motifs</module>
		<module>PADL Generator</module>
		<module>PADL Generator PageRank</module>
		<module>PADL Micro-pattern Analysis</module>
		<module>PADL Refactorings</module>
		<module>PADL Serialiser DB4O</module>
		<module>PADL Serialiser JOS</module>
		<module>PADL Statements</module>
		<module>PADL Statements Creator AOL</module>
		<module>PADL Statements Creator ClassFile</module>
		<module>POM</module>
		<module>SAD</module>
		<module>SAD Rules Creator</module>
		<module>SQUAD</module>
	</modules>
</project>
